[project]
name = "openhound-template"
version = "0.0.1"
description = "OpenGraph collector template using OpenHound"
readme = "README.md"
requires-python = ">=3.13"


[dependency-groups]
dev = [
    "openhound @ git+https://github.com/SpecterOps/openhound.git",
    "pre-commit>=4.5.1",
    "pytest>=9.0.1",
    "ruff>=0.15.5",
    "mypy>=1.19.1",
    "griffe>=1.15.0",
]
