[project]
name = "{{ cookiecutter.project_slug}}"
version = "0.0.1"
description = "OpenGraph collector for {{ cookiecutter.target_service_slug}} using OpenFetch"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "openfetch @ git+https://github.com/specterops/openfetch.git"
]
authors = [
  {name = "{{ cookiecutter.author}}", email = "{{ cookiecutter.author_email }}"}
]

[dependency-groups]
dev = [
    "black>=25.9.0",
    "flake8>=7.3.0",
    "griffe>=1.15.0",
    "pre-commit>=4.5.1",
    "pytest>=9.0.1",
]
